// Mock data used to seed the database and to drive the static style guide.
// Shapes match lib/types so the seed maps cleanly onto the schema.
import type { FoodCategory, Listing } from "./types";
import type { RetrievalHours } from "./hours";

export const CURRENT_USER = { name: "You", role: "volunteer" as const };

// The restaurant account viewing the restaurant console.
export const RESTAURANT = "Saxbys — Commons";

// Drop-off locations with their real constraints. Variety here is what makes
// the recommendation/matching meaningful.
export const DROP_OFFS: {
  name: string;
  acceptedCategories: FoodCategory[];
  refrigerated: boolean;
  capacity: number;
  notes: string;
  lat: number;
  lng: number;
  retrievalHours?: RetrievalHours;
}[] = [
  {
    name: "Community Fridge — 4th & Elm",
    acceptedCategories: ["prepared", "produce", "dairy", "bakery", "beverages"],
    refrigerated: true,
    capacity: 60,
    notes: "Refrigerated. No nut-containing items.",
    lat: 40.0362, // Malvern
    lng: -75.5138,
    retrievalHours: {
      mon: [{ open: "08:00", close: "20:00" }],
      tue: [{ open: "08:00", close: "20:00" }],
      wed: [{ open: "08:00", close: "20:00" }],
      thu: [{ open: "08:00", close: "20:00" }],
      fri: [{ open: "08:00", close: "20:00" }],
      sat: [{ open: "10:00", close: "16:00" }],
      sun: [],
    },
  },
  {
    name: "St. Mark's Shelter",
    acceptedCategories: ["prepared", "bakery", "packaged", "beverages"],
    refrigerated: false,
    capacity: 120,
    notes: "Hot meals welcome before 7pm. Not refrigerated.",
    lat: 40.0429, // Paoli
    lng: -75.4707,
    retrievalHours: {
      mon: [{ open: "11:00", close: "14:00" }, { open: "17:00", close: "19:00" }],
      tue: [{ open: "11:00", close: "14:00" }, { open: "17:00", close: "19:00" }],
      wed: [{ open: "11:00", close: "14:00" }, { open: "17:00", close: "19:00" }],
      thu: [{ open: "11:00", close: "14:00" }, { open: "17:00", close: "19:00" }],
      fri: [{ open: "11:00", close: "14:00" }, { open: "17:00", close: "19:00" }],
      sat: [],
      sun: [],
    },
  },
  {
    name: "Campus Pantry — Student Union",
    acceptedCategories: ["packaged", "bakery", "beverages", "produce"],
    refrigerated: false,
    capacity: 200,
    notes: "Shelf-stable & produce only. No prepared or dairy.",
    lat: 40.0454, // Berwyn
    lng: -75.4438,
  },
  {
    name: "Grace Kitchen",
    acceptedCategories: ["prepared", "dairy", "produce", "bakery", "packaged", "beverages"],
    refrigerated: true,
    capacity: 80,
    notes: "Full-service kitchen. Accepts everything.",
    lat: 40.0370, // Frazer
    lng: -75.5550,
  },
];

export const LISTINGS: Listing[] = [
  {
    // Demo: the one perpetually-urgent listing. lib/listings.ts pins this to
    // the <10 min band in dev (see ALWAYS_URGENT_TITLE) so the urgency UI —
    // tomato chip + pulse + 2-col feature — is always on screen to test.
    id: "PU-4821",
    title: "Mediterranean wraps & salads",
    imageUrl: "/food-wraps.jpg",
    source: "Saxbys — Commons",
    expiresAt: "6:51 PM",
    minutesLeft: 6,
    servings: 18,
    weightLbs: 14,
    distance: "0.4 mi",
    status: "open",
    category: "prepared",
    perishable: true,
    allergens: ["sesame (tahini)", "gluten"],
    tempHandling: "cold",
    notes:
      "Please ring the bell at the side (kitchen) door — the front will be locked after close. Ask for Sam. Some wraps contain tahini (sesame); the salads are nut-free but share a prep surface. Bring a flat tray or box — the containers stack but slide.",
  },
  {
    id: "PU-4822",
    title: "Bagels, pastries & coffee cake",
    imageUrl: "/food-bagels.jpg",
    source: "Bruegger's — Main St",
    expiresAt: "7:15 PM",
    minutesLeft: 48,
    servings: 40,
    weightLbs: 30,
    distance: "0.9 mi",
    status: "open",
    category: "bakery",
    perishable: false,
    allergens: ["walnuts", "poppy seed", "gluten"],
    tempHandling: "ambient",
    notes:
      "Everything boxed and ready at the back counter. A few items have walnuts or poppy seed — they're bagged separately and labeled. Coffee cake should stay flat so the icing doesn't smear.",
  },
  {
    id: "PU-4823",
    title: "Catered sandwich platters",
    imageUrl: "/food-sandwiches.jpg",
    source: "Conference Center",
    expiresAt: "8:30 PM",
    minutesLeft: 107,
    servings: 60,
    weightLbs: 48,
    distance: "1.1 mi",
    status: "open",
    category: "prepared",
    perishable: true,
    notes:
      "Check in with security at the loading dock — they'll point you to the catering fridge. Platters are heavy (~6 lbs each); a cart helps. Please take the cold packs too and leave them at the drop-off.",
  },
  {
    id: "PU-4824",
    title: "Soup, rolls & side salads",
    imageUrl: "/food-soup.jpg",
    source: "Dining Hall — North",
    expiresAt: "7:40 PM",
    minutesLeft: 57,
    servings: 35,
    weightLbs: 41,
    distance: "0.6 mi",
    status: "claimed",
    claimedBy: "Priya R.",
    dropOff: "Community Fridge — 4th & Elm",
    category: "prepared",
    perishable: true,
  },
  {
    id: "PU-4825",
    title: "Pizza by the slice",
    imageUrl: "/food-sandwiches.jpg",
    source: "Slice Co. — Quad",
    expiresAt: "6:30 PM",
    minutesLeft: 50,
    servings: 24,
    weightLbs: 26,
    distance: "0.3 mi",
    status: "in transit",
    claimedBy: "You",
    dropOff: "St. Mark's Shelter",
    category: "prepared",
    perishable: true,
  },
  {
    id: "PU-4831",
    title: "Chicken & rice trays",
    imageUrl: "/food-soup.jpg",
    source: "Greenhouse Cafe",
    expiresAt: "—",
    minutesLeft: 0,
    servings: 16,
    weightLbs: 18,
    distance: "0.6 mi",
    status: "taken home",
    claimedBy: "You",
    dropOff: "Community Fridge — 4th & Elm",
    category: "prepared",
    perishable: true,
    notes:
      "Fridge was locked by the time I got there — keeping these chilled overnight and dropping them tomorrow.",
  },
  {
    id: "PU-4818",
    title: "Roasted veg & grain bowls",
    imageUrl: "/food-soup.jpg",
    source: "Greenhouse Cafe",
    expiresAt: "5:55 PM",
    minutesLeft: 0,
    servings: 28,
    weightLbs: 25,
    distance: "0.8 mi",
    status: "delivered",
    claimedBy: "You",
    dropOff: "Community Fridge — 4th & Elm",
    category: "prepared",
    perishable: true,
  },
  {
    id: "PU-4815",
    title: "Assorted deli sandwiches",
    imageUrl: "/food-sandwiches.jpg",
    source: "Corner Market",
    expiresAt: "4:10 PM",
    minutesLeft: 0,
    servings: 15,
    weightLbs: 11,
    distance: "1.4 mi",
    status: "expired",
    category: "prepared",
    perishable: true,
  },
  {
    id: "PU-4811",
    title: "Pasta trays & garlic bread",
    imageUrl: "/food-soup.jpg",
    source: "Tony's Kitchen",
    expiresAt: "3:30 PM",
    minutesLeft: 0,
    servings: 50,
    weightLbs: 55,
    distance: "2.0 mi",
    status: "failed",
    claimedBy: "Sam O.",
    dropOff: "St. Mark's Shelter",
    category: "prepared",
    perishable: true,
  },
  {
    id: "PU-4826",
    title: "Cold brew & iced lattes",
    imageUrl: "/food-bagels.jpg",
    source: "Saxbys — Commons",
    expiresAt: "7:00 PM",
    minutesLeft: 52,
    servings: 30,
    weightLbs: 38,
    distance: "0.4 mi",
    status: "claimed",
    claimedBy: "Marcus L.",
    dropOff: "Community Fridge — 4th & Elm",
    category: "beverages",
    perishable: false,
  },
  {
    id: "PU-4809",
    title: "Breakfast sandwiches",
    imageUrl: "/food-sandwiches.jpg",
    source: "Saxbys — Commons",
    expiresAt: "10:30 AM",
    minutesLeft: 0,
    servings: 22,
    weightLbs: 16,
    distance: "0.4 mi",
    status: "delivered",
    claimedBy: "Dana K.",
    dropOff: "St. Mark's Shelter",
    category: "prepared",
    perishable: true,
  },
  // A second open listing in the "soon" band (10–35 min) so the demo feed shows
  // all three urgency bands at once: closing soon (PU-4821) · soon · open.
  {
    id: "PU-4827",
    title: "Garden salads & wraps",
    imageUrl: "/food-wraps.jpg",
    source: "Greenhouse Cafe",
    expiresAt: "7:05 PM",
    minutesLeft: 22,
    servings: 20,
    weightLbs: 12,
    distance: "0.8 mi",
    status: "open",
    category: "prepared",
    perishable: true,
    notes: "Dressings packed on the side in labeled cups — keep the trays upright.",
  },
  // Second claimed listing (someone else's hold) so the "Claimed & closed"
  // section reads as a real queue.
  {
    id: "PU-4828",
    title: "Fruit cups & yogurt parfaits",
    imageUrl: "/food-bagels.jpg",
    source: "Dining Hall — North",
    expiresAt: "7:20 PM",
    minutesLeft: 44,
    servings: 26,
    weightLbs: 18,
    distance: "0.6 mi",
    status: "claimed",
    claimedBy: "Jordan T.",
    dropOff: "Community Fridge — 4th & Elm",
    category: "dairy",
    perishable: true,
  },
  // Two more in-transit pickups (other volunteers) so "in transit" isn't a
  // single card.
  {
    id: "PU-4829",
    title: "Veggie burrito bowls",
    imageUrl: "/food-wraps.jpg",
    source: "Slice Co. — Quad",
    expiresAt: "6:45 PM",
    minutesLeft: 33,
    servings: 18,
    weightLbs: 20,
    distance: "0.3 mi",
    status: "in transit",
    claimedBy: "Priya R.",
    dropOff: "Grace Kitchen",
    category: "prepared",
    perishable: true,
  },
  {
    id: "PU-4830",
    title: "Bottled juices & seltzers",
    imageUrl: "/food-bagels.jpg",
    source: "Corner Market",
    expiresAt: "8:00 PM",
    minutesLeft: 70,
    servings: 48,
    weightLbs: 44,
    distance: "1.4 mi",
    status: "in transit",
    claimedBy: "Marcus L.",
    dropOff: "Campus Pantry — Student Union",
    category: "beverages",
    perishable: false,
  },
  // Third delivered rescue, so the completed history feels lived-in.
  {
    id: "PU-4808",
    title: "Muffins & scones",
    imageUrl: "/food-bagels.jpg",
    source: "Bruegger's — Main St",
    expiresAt: "9:15 AM",
    minutesLeft: 0,
    servings: 30,
    weightLbs: 14,
    distance: "0.9 mi",
    status: "delivered",
    claimedBy: "Priya R.",
    dropOff: "Campus Pantry — Student Union",
    category: "bakery",
    perishable: false,
  },
  // Second expired (nobody claimed in time).
  {
    id: "PU-4812",
    title: "Garden vegetable soup",
    imageUrl: "/food-soup.jpg",
    source: "Tony's Kitchen",
    expiresAt: "2:45 PM",
    minutesLeft: 0,
    servings: 20,
    weightLbs: 22,
    distance: "2.0 mi",
    status: "expired",
    category: "prepared",
    perishable: true,
  },
  // Second failed (claimed but not completed) — shown non-punitively.
  {
    id: "PU-4810",
    title: "Taco bar trays",
    imageUrl: "/food-wraps.jpg",
    source: "Conference Center",
    expiresAt: "3:10 PM",
    minutesLeft: 0,
    servings: 40,
    weightLbs: 38,
    distance: "1.1 mi",
    status: "failed",
    claimedBy: "Dana K.",
    dropOff: "St. Mark's Shelter",
    category: "prepared",
    perishable: true,
  },
];
